<?xml version="1.0" encoding="UTF-8" ?>
<!-- 엘리먼트 나열 - 여러 개 중에 한 개의 엘리먼트 선택 II
<!ELEMENT 이름 (태그1 | 태그2 | 태그3)*>
- 내용이 없는 태그 
 -->
<!DOCTYPE items [
<!ELEMENT items (book|dvd)*>
<!ELEMENT book (title,author+,press,page,description?,photo*,(cd|tape|usb)?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT cd EMPTY>
<!ELEMENT tape EMPTY>
<!ELEMENT usb EMPTY>
<!ELEMENT dvd (title,price)>
<!ELEMENT price (#PCDATA)>
]>
<items>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
    </book>
    <dvd>
        <title>aaaa</title>
        <price>20000</price>
    </dvd>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
    </book>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
        <page>300</page>
    </book>
    <dvd>
        <title>aaaa</title>
        <price>20000</price>
    </dvd>
</items>






