<?xml version="1.0" encoding="UTF-8" ?>
<!-- 엘리먼트 타입 - 여러 개의 자식 태그
<!ELEMENT 이름 (자식태그명, 자식태그명, ...)>
- 자식 태그를 나열할 때는 순서를 지켜야 한다.
 -->
<!DOCTYPE books [
<!ELEMENT books (book)*>
<!ELEMENT book (title,author,press)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
]>
<books>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
    </book>
    <book>
        <title>aaaa</title>
        <author>bbbb</author>
        <press>cccc</press>
    </book>
</books>